language: elixir
matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4.1
    - otp_release: 19.0
      elixir: 1.3.2
sudo: false
notifications:
  email: false
script:
  - mix test
  - mix credo --strict
